### ISSUE TITLE
Expo app crashes on start up.

### ISSUE THREAD

**Issue by DealPete** [shanhuiyang/TypeScript-MERN-Starter#27] opened 2019-12-10 21:13 UTC
Hi guys,

I'm testing out the app, but I can't get it to run on mobile. The web version works fine. I start with

git clone ...
cd ...
yarn
mongod
yarn start

The expo package starts properly and it loads 100% of the javascript code from my computer, but then red boxes with:

[17:34:45] TypeError: undefined is not an object (evaluating 'this.props.state.articles.data')
[2] * src/Article/ArticleList.tsx:42:50 in render
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11581:21 in finishClassComponent
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11509:4 in updateClassComponent
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17276:21 in performUnitOfWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17316:41 in workLoop
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17417:15 in renderRoot
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
[2] - node_modules/react/cjs/react.development.js:325:31 in <unknown>
[2] * App.tsx:59:22 in componentDidMount$
[2] - node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
[2] - node_modules/regenerator-runtime/runtime.js:271:30 in invoke
[2] - ... 13 more stack frames from framework internals
[2] 
[2] [17:34:48] Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI., RootErrorBoundary
[2] - node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:638:36 in warningWithoutStack
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15918:16 in callback
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13857:16 in callCallback
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13901:19 in commitUpdateEffects
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13892:22 in commitUpdateQueue
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15123:10 in commitLifeCycles
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:16636:8 in commitAllLifeCycles
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:93:15 in invokeGuardedCallbackImpl
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:318:36 in invokeGuardedCallback
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:16876:8 in commitRoot
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18501:17 in <unknown>
[2] - node_modules/scheduler/cjs/scheduler.development.js:697:23 in unstable_runWithPriority
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18499:4 in completeRoot
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18427:21 in performWorkOnRoot
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
[2] - node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
[2] - node_modules/react/cjs/react.development.js:325:31 in <unknown>
[2] * App.tsx:59:22 in componentDidMount$
[2] - node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
[2] - node_modules/regenerator-runtime/runtime.js:271:30 in invoke
[2] - ... 13 more stack frames from framework internals

**Comment by shanhuiyang** [comment] 2019-12-11 10:17
@DealPete  thanks for your report.

1. I have fixed the build issue in Expo project, you can pull the latest code and try again.
2. The issue you reported is a build break caused by usual code change. Because there is no check for Expo project before we complete the PR, we cannot prohibit this kind of issue happen again now. I would like to keep this issue open before I add some build checks for Expo project.

Again, thanks for your help.

**Comment by shanhuiyang** [comment] 2019-12-20 11:47
@DealPete The remaining issue is resolved by [PR#49](https://github.com/shanhuiyang/TypeScript-MERN-Starter/pull/49).
From now on each PR will be check with Typescript build on mobile part.
Close this issue.

**Closed by shanhuiyang** 2019-12-20 11:47 UTC
